import { catalogDocuments } from "./catalogs.mjs";

const { ApplicationV2, HandlebarsApplicationMixin } = foundry.applications.api;
export class AlternityCompendiumBrowser extends HandlebarsApplicationMixin(ApplicationV2) {
  static DEFAULT_OPTIONS = { id: "alternity-compendium-browser", classes: ["alternity2e", "catalog-browser"], position: { width: 920, height: 760 }, window: { title: "Alternity 2e Catalog Browser" } };
  static PARTS = { main: { template: "systems/alternity2e/templates/compendium-browser.hbs" } };
  async _prepareContext(options) { const context = await super._prepareContext(options), rows = catalogDocuments().map(source => ({ ...source, category: source.system.category || source.type, search: `${source.name} ${source.type} ${source.system.category || ""} ${source.system.description || ""}`.toLowerCase() })); return foundry.utils.mergeObject(context, { rows, actors: game.actors.filter(actor => actor.isOwner), types: [...new Set(rows.map(row => row.type))].sort() }, { inplace: false }); }
  async _onRender(context, options) { await super._onRender(context, options); const filter = () => { const query = this.element.querySelector("[data-catalog-search]").value.trim().toLowerCase(), type = this.element.querySelector("[data-catalog-type]").value; for (const row of this.element.querySelectorAll("[data-catalog-row]")) row.hidden = Boolean(type && row.dataset.type !== type || query && !row.dataset.search.includes(query)); }; this.element.querySelector("[data-catalog-search]")?.addEventListener("input", filter); this.element.querySelector("[data-catalog-type]")?.addEventListener("change", filter); this.element.querySelectorAll("[data-catalog-add]").forEach(button => button.addEventListener("click", () => this.#add(button.dataset.catalogAdd))); }
  async #add(key) { const actor = game.actors.get(this.element.querySelector("[data-catalog-actor]")?.value); if (!actor?.isOwner) return ui.notifications.warn("Choose an Actor you own."); const [type, sourceId] = key.split(":"); const source = catalogDocuments().find(row => row.type === type && row.system.sourceId === sourceId); if (!source) return; if (actor.items.some(item => item.type === type && item.system.sourceId === sourceId)) return ui.notifications.info(`${source.name} is already on ${actor.name}.`); await actor.createEmbeddedDocuments("Item", [source]); ui.notifications.info(`Added ${source.name} to ${actor.name}.`); }
}
