import { catalogDocuments } from "./catalogs.mjs";
import { ACTOR_SCHEMA_VERSION, exportItemState } from "./migrations.mjs";

export async function importStandaloneCharacter(character, { actor = null } = {}) {
  if (!character || typeof character !== "object" || Array.isArray(character)) throw new Error("The selected file is not a valid character.");
  if (!character.abilities || !character.skills || !character.wounds) throw new Error("The character file is missing abilities, skills, or wounds.");
  if (!actor && !game.user.can("ACTOR_CREATE")) throw new Error("You do not have permission to create Actors.");
  if (actor && !actor.isOwner) throw new Error("You do not have permission to update this Actor.");
  const actorSource = { name: character.identity?.name || actor?.name || "Imported Hero", type: actor?.type || character.actorType || "hero", system: {
    schemaVersion: ACTOR_SCHEMA_VERSION, level: character.level || 1, heroPoints: character.heroPoints ?? 1, abilities: character.abilities, wounds: character.wounds,
    speciesId: character.species || "human", archetypeId: character.archetype || "", mandatedTalentId: character.mandatedTalent || "", campaign: character.campaign,
    identity: { player: character.identity?.player || "", concept: character.identity?.concept || "", background: character.identity?.background || "", goals: character.identity?.goals || "", connections: character.identity?.connections || "", notes: character.identity?.notes || "" },
    build: character.build || actor?.system.build, play: character.play || { round: 1, impulse: 1, statuses: [], effects: [], damageLog: [], lastDamage: null, challenges: [], recovery: [] }, npc: character.npc || actor?.system.npc, creature: character.creature || actor?.system.creature, drone: character.drone || actor?.system.drone, vehicle: character.vehicle || actor?.system.vehicle, starship: character.starship || actor?.system.starship, advancement: character.advancement || [], migrationHistory: character.migrationHistory || []
  }};
  if (actor) await actor.update(actorSource); else actor = await Actor.create(actorSource);
  const sources = catalogDocuments(), wanted = new Set([...(character.talents || []).map(id => `talent:${id}`), ...(character.gear || []).map(id => `gear:${id}`), ...(character.gear || []).map(id => `weapon:${id}`), ...(character.gear || []).map(id => `armor:${id}`), ...(character.gear || []).map(id => `tool:${id}`)]);
  const items = sources.filter(x => wanted.has(`${x.type}:${x.system.sourceId}`));
  if (Array.isArray(character.itemStates)) { items.length = 0; for (const state of character.itemStates) { if (state.custom) { const custom = foundry.utils.deepClone(state.custom); delete custom._id; items.push(custom); continue; } const source = sources.find(entry => entry.type === state.type && entry.system.sourceId === state.sourceId); if (source) items.push(foundry.utils.mergeObject(source, { system: { quantity: state.quantity ?? 1, equipped: state.equipped ?? true, upgrades: state.upgrades || [], featureStates: state.featureStates || {}, ammo: state.ammo || source.system.ammo } }, { inplace: false, recursive: true })); } for (const id of character.talents || []) { const source = sources.find(entry => entry.type === "talent" && entry.system.sourceId === id); if (source) items.push(source); } }
  for (const [id, state] of Object.entries(character.skills || {})) { const source = sources.find(x => x.type === "skill" && x.system.sourceId === id); if (source) items.push(foundry.utils.mergeObject(source, { system: { ranks: state.ranks || 0, keyAbility: state.keyAbility || source.system.keyAbility } }, { inplace: false })); }
  if (actor.items.size) await actor.deleteEmbeddedDocuments("Item", actor.items.map(item => item.id));
  const created = await actor.createEmbeddedDocuments("Item", items); if (Array.isArray(character.itemStates)) { const pools = created.filter(item => item.system.metadata?.ammoPool); for (const weapon of created.filter(item => item.type === "weapon")) { const state = character.itemStates.find(entry => entry.type === "weapon" && (entry.sourceId && entry.sourceId === weapon.system.sourceId || !entry.sourceId && entry.name === weapon.name)), pool = state?.ammoResourceName ? pools.find(entry => entry.name === state.ammoResourceName) : null; if (pool) await weapon.update({ "system.ammo.resourceId": pool.id }); } } return actor;
}

export function exportStandaloneCharacter(actor) {
  const byType = type => actor.items.filter(i => i.type === type);
  const equipment = actor.items.filter(i => ["weapon", "armor", "tool", "gear"].includes(i.type));
  return { schemaVersion: ACTOR_SCHEMA_VERSION, appVersion: `foundry-${game.system.version}`, rulesVersion: "alternity-core-2018", id: actor.id, actorType: actor.type, identity: { name: actor.name, ...actor.system.identity }, campaign: actor.system.campaign, level: actor.system.level, heroPoints: actor.system.heroPoints, abilities: actor.system.abilities, species: actor.system.speciesId, archetype: actor.system.archetypeId, mandatedTalent: actor.system.mandatedTalentId, talents: byType("talent").map(i => i.system.sourceId), skills: Object.fromEntries(byType("skill").map(i => [i.system.sourceId, { ranks: i.system.ranks, keyAbility: i.system.keyAbility, specialties: [] }])), gear: equipment.map(i => i.system.sourceId).filter(Boolean), itemStates: equipment.map(exportItemState), gearUpgrades: Object.fromEntries(equipment.filter(item => item.system.sourceId).map(item => [item.system.sourceId, [...(item.system.upgrades || [])]])), gearCustomizations: Object.fromEntries(equipment.filter(item => item.system.sourceId).map(item => [item.system.sourceId, { upgrades: [...(item.system.upgrades || [])].filter(id => id.startsWith("custom-")), featureStates: item.system.featureStates || {} }])), customGear: equipment.filter(item => !item.system.sourceId).map(item => item.toObject()), wounds: actor.system.wounds, build: actor.system.build, play: actor.system.play, npc: actor.system.npc, creature: actor.system.creature, drone: actor.system.drone, vehicle: actor.system.vehicle, starship: actor.system.starship, advancement: actor.system.advancement, overrides: [], migrationHistory: actor.system.migrationHistory };
}
