export function registerSettings() {
  game.settings.register("alternity2e", "installPrivateCatalogs", { name: "Install Core Rulebook compendiums", hint: "Builds categorized world compendiums from the bundled personal-use rulebook catalog when the world opens.", scope: "world", config: true, type: Boolean, default: true });
  game.settings.register("alternity2e", "lethality", { name: "Lethality", scope: "world", config: true, type: String, choices: { low: "Low", standard: "Standard", high: "High" }, default: "standard" });
  game.settings.register("alternity2e", "ammunitionTracking", { name: "Ordinary ammunition reserves", hint: "Loaded ammunition is always tracked. Abstract reserves allow ordinary reloads whenever ammunition is reasonably available; Limited reserves also track spare magazines, cells, shells, and warheads.", scope: "world", config: true, type: String, choices: { abstract: "Abstract reserves (recommended)", limited: "Limited reserves" }, default: "abstract" });
  game.settings.register("alternity2e", "damageAuthority", { name: "Player damage authority", hint: "Request mode sends damage against unowned Actors to the GM. Owner mode also lets owners directly modify their own Actor.", scope: "world", config: true, type: String, choices: { request: "GM approval for unowned targets (recommended)", owner: "Owners may apply damage to their own Actors" }, default: "request" });
  game.settings.register("alternity2e", "inventoryAuthority", { name: "Player inventory authority", hint: "Choose whether owners can add, remove, and adjust their own equipment or whether those changes require a GM.", scope: "world", config: true, type: String, choices: { owner: "Actor owners (recommended)", gm: "GM only" }, default: "owner" });
  game.settings.register("alternity2e", "buildLockDefault", { name: "Lock completed hero builds", hint: "When enabled, abilities, origin, skills, talents, and level advancement remain locked until a GM opens advancement.", scope: "world", config: true, type: Boolean, default: true });
  game.settings.register("alternity2e", "npcRollMode", { name: "NPC roll visibility", scope: "world", config: true, type: String, choices: { publicroll: "Public", gmroll: "Private GM roll", blindroll: "Blind GM roll" }, default: "gmroll" });
  game.settings.register("alternity2e", "heroicMode", { name: "Hero Point campaign mode", scope: "world", config: true, type: String, choices: { standard: "Standard (1 at adventure start)", high: "High heroic (5 at adventure start)" }, default: "standard" });
  game.settings.register("alternity2e", "tacticalAutomation", { name: "Tactical automation", hint: "Automatic mode measures token range and applies structured cover and size modifiers when present.", scope: "world", config: true, type: String, choices: { assisted: "Assisted (recommended)", automatic: "Automatic", manual: "Manual" }, default: "assisted" });
  game.settings.register("alternity2e", "catalogVersion", { scope: "world", config: false, type: String, default: "" });
}
