import { archetypes, species, talents, catalogDocuments, refreshActorSources, refreshCompendiums } from "./catalogs.mjs";
import { AlternityCreationWizard } from "./wizard.mjs";
import { positionFromTick } from "./impulse-rules.mjs";
import { consolidateActorItems } from "./inventory.mjs";
import { reloadPlan, specialAmmoEffect } from "./ammunition.mjs";
import { actorAccess, canConfigureActor, canManageInventory, canPlayActor, isGM, requireAuthority } from "./authority.mjs";
import { newChallenge } from "./trackers.mjs";
import { installUpgrade, upgradeEligibleFor } from "./upgrades.mjs";
import { pointBuyCosts } from "../data/abilities.js";
import { recordOrRequestChallenge } from "./requests.mjs";

const { ActorSheetV2, ItemSheetV2 } = foundry.applications.sheets;
const { HandlebarsApplicationMixin } = foundry.applications.api;

export class AlternityActorSheet extends HandlebarsApplicationMixin(ActorSheetV2) {
  static DEFAULT_OPTIONS = {
    classes: ["alternity2e", "actor-sheet"], position: { width: 1100, height: 820 }, form: { closeOnSubmit: false },
    actions: {
      rollSkill: AlternityActorSheet.#rollSkill, rollWeapon: AlternityActorSheet.#rollWeapon, applyDamage: AlternityActorSheet.#applyDamage,
      heroUp: AlternityActorSheet.#heroUp, heroDown: AlternityActorSheet.#heroDown, nextImpulse: AlternityActorSheet.#nextImpulse,
      toggleWound: AlternityActorSheet.#toggleWound, toggleStatus: AlternityActorSheet.#toggleStatus, exportCharacter: AlternityActorSheet.#exportCharacter,
      importCharacter: AlternityActorSheet.#importCharacter, adjustAbility: AlternityActorSheet.#adjustAbility, adjustRank: AlternityActorSheet.#adjustRank,
      toggleEquip: AlternityActorSheet.#toggleEquip, editItem: AlternityActorSheet.#editItem, deleteItem: AlternityActorSheet.#deleteItem,
      reload: AlternityActorSheet.#reload, recover: AlternityActorSheet.#recover, newScene: AlternityActorSheet.#newScene, advanceLevel: AlternityActorSheet.#advanceLevel,
      refreshSources: AlternityActorSheet.#refreshSources, rebuildCompendiums: AlternityActorSheet.#rebuildCompendiums, creationWizard: AlternityActorSheet.#creationWizard,
      scheduleAction: AlternityActorSheet.#scheduleAction, setCombatModifier: AlternityActorSheet.#setCombatModifier, react: AlternityActorSheet.#react,
      consolidateItems: AlternityActorSheet.#consolidateItems, adjustQuantity: AlternityActorSheet.#adjustQuantity, adjustReserve: AlternityActorSheet.#adjustReserve,
      toggleSpeedLoader: AlternityActorSheet.#toggleSpeedLoader, toggleSpecialSupply: AlternityActorSheet.#toggleSpecialSupply
      , useHeroPoint: AlternityActorSheet.#useHeroPoint, awardHeroPoint: AlternityActorSheet.#awardHeroPoint, undoDamage: AlternityActorSheet.#undoDamage,
      rollMortality: AlternityActorSheet.#rollMortality, scheduleRecovery: AlternityActorSheet.#scheduleRecovery, rollRecovery: AlternityActorSheet.#rollRecovery,
      stabilizeMortality: AlternityActorSheet.#stabilizeMortality, rollChallenge: AlternityActorSheet.#rollChallenge,
      resistEffect: AlternityActorSheet.#resistEffect, removeEffect: AlternityActorSheet.#removeEffect, addEffect: AlternityActorSheet.#addEffect,
      addChallenge: AlternityActorSheet.#addChallenge, advanceChallenge: AlternityActorSheet.#advanceChallenge,
      toggleBuildLock: AlternityActorSheet.#toggleBuildLock, openAdvancement: AlternityActorSheet.#openAdvancement, installUpgrade: AlternityActorSheet.#installUpgrade,
      rollNpcKey: AlternityActorSheet.#rollNpcKey, rollNpcSecondary: AlternityActorSheet.#rollNpcSecondary, shiftAttitude: AlternityActorSheet.#shiftAttitude, vehicleControl: AlternityActorSheet.#vehicleControl, droneCommand: AlternityActorSheet.#droneCommand
    }
  };
  static PARTS = { main: { template: "systems/alternity2e/templates/actor-sheet.hbs" } };
  tabGroups = { primary: "play" };
  async _prepareContext(options) {
    const context = await super._prepareContext(options), actor = this.actor, s = actor.system;
    if (!s.derived?.durability) actor.prepareDerivedData();
    if (!s.derived?.durability) throw new Error(`Alternity 2e could not prepare derived statistics for ${actor.name}. Check the console for the earlier prepareDerivedData error.`);
    const skillItems = actor.items.filter(i => i.type === "skill").sort((a, b) => a.system.category.localeCompare(b.system.category) || a.name.localeCompare(b.name));
    const archetype = archetypes.find(row => row.id === s.archetypeId);
    const combat = game.combat?.started ? game.combat : null, combatant = combat?.combatantForActor?.(actor), nextPosition = combatant ? positionFromTick(Number(combatant.getFlag("alternity2e", "nextTick") || 1)) : null;
    const access = actorAccess(actor);
    return foundry.utils.mergeObject(context, {
      actor, system: s, editable: this.isEditable, access, isGM: access.isGM, isHero: actor.type === "hero", isNpc: actor.type === "npc", isCreature: actor.type === "creature", isDrone: actor.type === "drone", isVehicle: actor.type === "vehicle", rankCap: Math.min(4 + s.level, 10), speciesOptions: species, archetypeOptions: archetypes, load: s.derived.load, limitedAmmo: game.settings.get("alternity2e", "ammunitionTracking") === "limited",
      combatState: combatant ? { active: true, ready: combat.isReady(combatant), readied: Boolean(combatant.getFlag("alternity2e", "readied")), nextRound: nextPosition.round, nextImpulse: nextPosition.impulse, lastAction: combatant.getFlag("alternity2e", "lastAction") || "None", modifier: combatant.getFlag("alternity2e", "pendingModifier") } : { active: false },
      mandatedOptions: talents.filter(row => row.entry && (archetype?.id === "freeform" || archetype?.mandatedTalents.includes(row.id))),
      abilities: Object.entries(s.abilities).map(([id, value]) => ({ id, label: game.i18n.localize(`A2E.Ability.${id}`), value })),
      wounds: [["mortal", "16+", "Mortal wound (cannot act)"], ["critical", "13–15", "Critical wound (–3 die steps)"], ["serious", "10–12", "Serious wound (–2 die steps)"], ["moderate", "7–9", "Moderate wound (–1 die step)"], ["light", "4–6", "Light wound (no effect)"], ["graze", "1–3", "Graze (no effect)"]].map(([id, range, label]) => ({ id, range, label, current: s.wounds[id], recoverable: ["moderate", "serious", "critical"].includes(id) && s.wounds[id] > 0, boxes: Array.from({ length: s.derived.durability[id] }, (_, index) => ({ index, marked: index < s.wounds[id] })) })),
      skillGroups: Object.entries(skillItems.reduce((all, item) => ((all[item.system.category] ??= []).push({ item, target: 20 - s.abilities[item.system.keyAbility] - item.system.ranks, steps: s.derived.woundPenalty + actor.statusSteps }), all), {})).map(([name, rows]) => ({ name, rows })),
      attacks: actor.items.filter(i => i.type === "weapon"), talents: actor.items.filter(i => i.type === "talent"),
      equipmentGroups: Object.entries(actor.items.filter(i => ["weapon", "armor", "tool", "gear", "upgrade"].includes(i.type)).reduce((all, item) => ((all[item.system.category || item.type] ??= []).push(item), all), {})).map(([name, items]) => ({ name, items })),
      statuses: Object.entries({ blinded: "Blinded", dazed: "Dazed", dead: "Dead", distracted: "Distracted", grappled: "Grappled", impaired: "Impaired", prone: "Prone", slowed: "Slowed", weakened: "Weakened", incapacitated: "Incapacitated", insane: "Insane", "off-balance": "Off-Balance", stun: "Stunned", "damage-over-time": "Damage Over Time" }).map(([id, label]) => ({ id, label, active: s.play.statuses.includes(id), playerToggle: id === "prone" })),
      effects: s.play.effects, mortality: s.play.mortality, recovery: s.play.recovery, challenges: s.play.challenges.filter(challenge => access.isGM || !challenge.secret)
      , upgradeOptions: catalogDocuments().filter(item => item.type === "upgrade"), upgradeTargets: actor.items.filter(item => ["weapon", "armor", "tool"].includes(item.type))
    }, { inplace: false });
  }
  static async #rollSkill(event, target) { if (!requireAuthority(canPlayActor(this.actor), "You do not control this Actor.")) return; const combat = game.combat?.started ? game.combat : null, combatant = combat?.combatantForActor?.(this.actor); if (combat && !combat.canActNow(combatant)) return ui.notifications.warn(`${this.actor.name} is not ready to act in this impulse.`); const modifier = combat?.getModifier?.(this.actor, "skill"); await this.actor.rollSkill(this.actor.items.get(target.dataset.itemId), { steps: Number(modifier?.steps || 0) }); if (combat) await this.actor.scheduleCombatAction(3, { label: modifier?.label || "Use a skill or tool", kind: "skill" }); }
  static async #rollWeapon(event, target) { if (requireAuthority(canPlayActor(this.actor), "You do not control this Actor.")) await this.actor.rollWeapon(this.actor.items.get(target.dataset.itemId)); }
  static async #applyDamage() { if (!requireAuthority(game.user.isGM || game.settings.get("alternity2e", "damageAuthority") === "owner" && this.actor.isOwner, "Damage must be approved by the GM.")) return; const form = this.element.querySelector(".damage-form"); await this.actor.applyDamage(Number(form.querySelector("[name=damage]").value), form.querySelector("[name=damageType]").value); }
  static async #heroUp() { await this.actor.awardHeroPoint(1); }
  static async #heroDown() { if (requireAuthority(canPlayActor(this.actor), "You do not control this Actor.")) await this.actor.spendHeroPoint(); }
  static async #nextImpulse() { if (!requireAuthority(game.user.isGM, "Only the GM can advance the shared clock.")) return; if (game.combat?.started && game.combat.advanceImpulse) await game.combat.advanceImpulse(); }
  static async #toggleWound(event, target) { if (!requireAuthority(game.user.isGM || game.settings.get("alternity2e", "damageAuthority") === "owner" && this.actor.isOwner, "Wounds are GM-authoritative.")) return; const row = target.dataset.row, index = Number(target.dataset.index), current = this.actor.system.wounds[row]; await this.actor.update({ [`system.wounds.${row}`]: current === index + 1 ? index : index + 1 }); }
  static async #toggleStatus(event, target) { const id = target.dataset.status; if (!requireAuthority(game.user.isGM || this.actor.isOwner && id === "prone", "Only the GM can directly impose or clear that condition.")) return; const values = [...this.actor.system.play.statuses], adding = !values.includes(id), next = adding ? [...values, id] : values.filter(x => x !== id); await this.actor.update({ "system.play.statuses": next }); if (adding && id === "stun" && game.combat?.started) { const combatant = game.combat.combatantForActor?.(this.actor); if (combatant) await game.combat.delayNextAction(combatant, 3, "Stun"); } }
  static async #adjustAbility(event, target) { if (!requireAuthority(canConfigureActor(this.actor), "This build is locked. Ask the GM to open creation or advancement.")) return; const id = target.dataset.ability, value = Math.clamp(this.actor.system.abilities[id] + Number(target.dataset.delta), 3, 7), scores = { ...this.actor.system.abilities, [id]: value }, spent = Object.values(scores).reduce((sum, score) => sum + Number(pointBuyCosts[score] ?? 999), 0); if (spent > this.actor.system.campaign.pointBuy) return ui.notifications.warn(`That change exceeds the ${this.actor.system.campaign.pointBuy}-point ability budget.`); const selectedSpecies = species.find(row => row.id === this.actor.system.speciesId), invalid = (selectedSpecies?.requirements || []).find(rule => rule.ability === id && (rule.op === ">=" ? value < rule.value : value > rule.value)); if (invalid) return ui.notifications.warn(`${selectedSpecies.name} requires ${id} ${invalid.op} ${invalid.value}.`); await this.actor.update({ [`system.abilities.${id}`]: value }); }
  static async #adjustRank(event, target) { if (!requireAuthority(canConfigureActor(this.actor), "This build is locked. Ask the GM to open advancement.")) return; const item = this.actor.items.get(target.dataset.itemId), delta = Number(target.dataset.delta), old = Number(item.system.ranks || 0), cap = Math.min(4 + this.actor.system.level, 10); if (delta > 0 && this.actor.system.build.advancementOpen && this.actor.system.build.skillPointsAvailable < 1) return ui.notifications.warn("No advancement skill points remain."); if (delta < 0 && this.actor.system.build.advancementOpen && this.actor.system.build.retrainingAvailable < 1) return ui.notifications.warn("The two retrainable skill points have already been reassigned."); if (delta > 0 && !this.actor.system.build.advancementOpen && this.actor.system.level === 1 && this.actor.items.filter(entry => entry.type === "skill").reduce((sum, entry) => sum + Number(entry.system.ranks || 0), 0) >= 35) return ui.notifications.warn("All 35 starting skill points are already spent."); const next = Math.clamp(old + delta, 0, cap); await item.update({ "system.ranks": next }); if (this.actor.system.build.advancementOpen && next !== old) { const change = next - old, update = { "system.build.skillPointsAvailable": Math.max(0, this.actor.system.build.skillPointsAvailable - change) }; if (change < 0) update["system.build.retrainingAvailable"] = Math.max(0, this.actor.system.build.retrainingAvailable + change); await this.actor.update(update); } }
  static async #toggleEquip(event, target) { if (!requireAuthority(canManageInventory(this.actor), "Inventory changes require GM approval.")) return; const item = this.actor.items.get(target.dataset.itemId), equipping = !item.system.equipped, isScreen = (item.system.special || []).some(value => /^Screen$/i.test(value)); if (equipping && item.type === "armor") { const others = this.actor.items.filter(entry => entry.id !== item.id && entry.type === "armor" && entry.system.equipped && (isScreen ? (entry.system.special || []).some(value => /^Screen$/i.test(value)) : !(entry.system.special || []).some(value => /^(screen|cover|deflect|bonus resistance)/i.test(value)))).map(entry => ({ _id: entry.id, "system.equipped": false })); if (others.length) await this.actor.updateEmbeddedDocuments("Item", others); } await item.update({ "system.equipped": equipping }); }
  static async #editItem(event, target) { this.actor.items.get(target.dataset.itemId)?.sheet.render(true); }
  static async #deleteItem(event, target) { const item = this.actor.items.get(target.dataset.itemId), talent = item?.type === "talent"; if (!requireAuthority(talent ? canConfigureActor(this.actor) : canManageInventory(this.actor), talent ? "The build is locked." : "Inventory changes require GM approval.")) return; if (talent && this.actor.items.some(entry => entry.type === "talent" && entry.system.parentId === item.system.sourceId)) return ui.notifications.warn(`${item.name} is required by another purchased talent.`); if (talent && item.system.sourceId === this.actor.system.mandatedTalentId) return ui.notifications.warn("The mandated talent cannot be retrained directly."); if (talent && this.actor.system.build.advancementOpen && !this.actor.system.build.talentRetrainingAvailable) return ui.notifications.warn("The level's talent retraining has already been used."); await this.actor.deleteEmbeddedDocuments("Item", [target.dataset.itemId]); if (talent && this.actor.system.build.advancementOpen) await this.actor.update({ "system.build.talentRetrainingAvailable": false, "system.build.talentChoicesAvailable": this.actor.system.build.talentChoicesAvailable + 1 }); }
  static async #adjustQuantity(event, target) { if (!requireAuthority(canManageInventory(this.actor), "Inventory changes require GM approval.")) return; const item = this.actor.items.get(target.dataset.itemId); if (!item) return; await item.update({ "system.quantity": Math.max(1, Number(item.system.quantity || 1) + Number(target.dataset.delta || 0)) }); }
  static async #adjustReserve(event, target) { if (!requireAuthority(canManageInventory(this.actor), "Inventory changes require GM approval.")) return; const item = this.actor.items.get(target.dataset.itemId); if (!item) return; await item.update({ "system.ammo.reserve": Math.max(0, Number(item.system.ammo.reserve || 0) + Number(target.dataset.delta || 0)) }); }
  static async #toggleSpeedLoader(event, target) { const item = this.actor.items.get(target.dataset.itemId); if (item?.system.sourceId === "revolver") await item.update({ "system.ammo.speedLoader": !item.system.ammo.speedLoader }); }
  static async #toggleSpecialSupply(event, target) { if (!requireAuthority(game.user.isGM, "Only the GM can grant or remove a special-ammunition supply.")) return; const item = this.actor.items.get(target.dataset.itemId); if (!item) return; await item.update({ "system.ammo.specialAvailable": !item.system.ammo.specialAvailable, "system.ammo.specialType": item.system.ammo.specialAvailable ? "normal" : item.system.ammo.specialType }); }
  static async #consolidateItems() { if (!requireAuthority(canManageInventory(this.actor), "Inventory changes require GM approval.")) return; const result = await consolidateActorItems(this.actor); ui.notifications.info(result.removed ? `Consolidated ${result.groups} duplicate groups and removed ${result.removed} duplicate Item records.` : "No duplicate source Items were found."); }
  static async #reload(event, target) { if (!requireAuthority(canPlayActor(this.actor), "You do not control this Actor.")) return; const item = this.actor.items.get(target.dataset.itemId), combat = game.combat?.started ? game.combat : null, forcedLimited = item.system.ammo.mode === "loadout" || /rocket/i.test(item.system.sourceId), limited = forcedLimited || game.settings.get("alternity2e", "ammunitionTracking") === "limited", plan = reloadPlan(item.system.ammo, { limited }); if (!plan.allowed) return ui.notifications.warn(plan.reason === "no-reserve" ? `${item.name} has no ${item.system.ammo.reserveUnit} remaining.` : `${item.name} does not need or cannot perform a reload.`); if (combat) { const result = await this.actor.scheduleCombatAction(plan.cost, { label: `Reload ${item.name}`, kind: "interact" }); if (!result) return; } await item.update({ "system.ammo.value": plan.nextValue, "system.ammo.reserve": plan.nextReserve }); }
  static async #scheduleAction(event, target) { if (!requireAuthority(canPlayActor(this.actor), "You do not control this Actor.")) return; const combat = game.combat, combatant = combat?.combatantForActor?.(this.actor); if (!combat?.started || !combatant) return ui.notifications.warn("Add this Actor to an active encounter first."); const kind = target.dataset.kind, cost = Number(target.dataset.cost || 1), label = target.dataset.label || target.textContent.trim(); if (kind === "ready") await combat.readyAction(combatant, this.element.querySelector("[name=readyTrigger]")?.value?.trim() || "Declared trigger"); else await combat.schedule(combatant, cost, { label, kind }); }
  static async #setCombatModifier(event, target) { const combat = game.combat, combatant = combat?.combatantForActor?.(this.actor); if (!combat?.started || !combatant) return ui.notifications.warn("Add this Actor to an active encounter first."); const definitions = { aim: { id: "aim", label: "Aim", kind: "attack", steps: 1, delay: 1 }, burst: { id: "burst", label: "Autofire burst", kind: "attack", delay: 1, ammoCost: 3, extraWounds: 1 }, fullauto: { id: "fullauto", label: "Full auto", kind: "attack", delay: 2, ammoCost: 10 }, charge: { id: "charge", label: "Charge", kind: "attack", delay: 1 }, evade: { id: "evade", label: "Evade", delay: 1, defensePenalty: -1 }, concentrate1: { id: "concentrate1", label: "Concentrate +1", kind: "skill", steps: 1, delay: 1 }, concentrate2: { id: "concentrate2", label: "Concentrate +2", kind: "skill", steps: 2, delay: 3 } }; const modifier = definitions[target.dataset.modifier]; if (modifier) await combat.setModifier(combatant, modifier); }
  static async #react() { const combat = game.combat, combatant = combat?.combatantForActor?.(this.actor); if (!combat?.started || !combatant) return ui.notifications.warn("Add this Actor to an active encounter first."); await combat.delayNextAction(combatant, 1, "Reaction"); }
  static async #recover(event, target) { if (requireAuthority(game.user.isGM, "Only the GM can resolve automatic recovery.")) await this.actor.recover(target.dataset.period); }
  static async #newScene() { if (!requireAuthority(game.user.isGM, "Only the GM can begin a new scene.")) return; for (const actor of game.actors) { await actor.recover?.("scene"); await actor.recoverNonlethal?.(); const effects = actor.system.play.effects.filter(effect => effect.durationType !== "scene"), statuses = actor.system.play.statuses.filter(status => effects.some(effect => effect.status === status) || !actor.system.play.effects.some(effect => effect.status === status)); const deviceUpdates = actor.items.filter(item => ["force-shield", "displacer-unit"].includes(item.system.sourceId)).map(item => { const metadata = foundry.utils.deepClone(item.system.metadata || {}); metadata.sceneUsed = false; metadata.shieldWounds = 0; metadata.shieldTrack = [false, false, false, false]; return { _id: item.id, "system.metadata": metadata }; }); if (deviceUpdates.length) await actor.updateEmbeddedDocuments("Item", deviceUpdates); await actor.update({ "system.play.scene": Number(actor.system.play.scene || 1) + 1, "system.play.round": 1, "system.play.impulse": 1, "system.play.effects": effects, "system.play.statuses": statuses }); } }
  static async #advanceLevel() { if (requireAuthority(game.user.isGM, "Only the GM awards levels.")) await this.actor.advanceLevel(); }
  static async #refreshSources() { if (!requireAuthority(canManageInventory(this.actor), "Inventory changes require GM approval.")) return; const count = await refreshActorSources(this.actor); ui.notifications.info(`Refreshed ${count} character Items from authoritative catalogs.`); }
  static async #rebuildCompendiums() { const count = await refreshCompendiums(); await game.settings.set("alternity2e", "catalogVersion", game.system.version); ui.notifications.info(`Rebuilt ${count} Alternity compendiums.`); }
  static async #useHeroPoint(event, target) { await this.actor.useHeroPoint(target.dataset.effect); }
  static async #awardHeroPoint(event, target) { await this.actor.awardHeroPoint(Number(target.dataset.amount || 1)); }
  static async #undoDamage() { await this.actor.undoLastDamage(); }
  static async #rollMortality() { if (requireAuthority(canPlayActor(this.actor), "You do not control this Actor.")) await this.actor.rollMortality(); }
  static async #stabilizeMortality(event, target) { if (!requireAuthority(game.user.isGM, "The GM records Medicine stabilization results.")) return; await this.actor.stabilizeMortality(Number(target.dataset.successes || 1)); }
  static async #scheduleRecovery(event, target) { if (!requireAuthority(game.user.isGM, "The GM schedules wound recovery.")) return; await this.actor.scheduleRecovery(target.dataset.row, { resting: true }); }
  static async #rollRecovery(event, target) { if (requireAuthority(canPlayActor(this.actor), "You do not control this Actor.")) await this.actor.rollRecovery(target.dataset.recoveryId); }
  static async #resistEffect(event, target) { if (requireAuthority(canPlayActor(this.actor), "You do not control this Actor.")) await this.actor.resistEffect(target.dataset.effectId); }
  static async #removeEffect(event, target) { await this.actor.removeEffect(target.dataset.effectId); }
  static async #addEffect() { if (!requireAuthority(game.user.isGM, "Only the GM can impose structured effects.")) return; const panel = this.element.querySelector(".effect-builder"), status = panel.querySelector("[name=effectStatus]").value, durationType = panel.querySelector("[name=effectDuration]").value, resistSkill = panel.querySelector("[name=effectResist]").value, required = Number(panel.querySelector("[name=effectRequired]").value || 1), duration = Number(panel.querySelector("[name=effectImpulses]").value || 0), effect = { id: foundry.utils.randomID(), status, source: panel.querySelector("[name=effectSource]").value || status, durationType, expiresTick: durationType === "impulses" ? Number(game.combat?.currentTick || 0) + duration : 0, resistMode: durationType === "passive" ? "passive" : resistSkill ? "active" : "none", resistSkill, required, progress: 0, damageSeverity: status === "damage-over-time" ? panel.querySelector("[name=effectDamage]").value : "" }; await this.actor.update({ "system.play.effects": [...this.actor.system.play.effects, effect], "system.play.statuses": [...new Set([...this.actor.system.play.statuses, status])] }); }
  static async #addChallenge() { if (!requireAuthority(game.user.isGM, "Only the GM can create challenge trackers.")) return; const panel = this.element.querySelector(".challenge-builder"), challenge = newChallenge({ name: panel.querySelector("[name=challengeName]").value || "Challenge", skillId: panel.querySelector("[name=challengeSkill]").value, target: Number(panel.querySelector("[name=challengeTarget]").value || 3), failureLimit: Number(panel.querySelector("[name=challengeFailures]").value || 3), interval: panel.querySelector("[name=challengeInterval]").value || "1 action", ownerId: this.actor.id, secret: panel.querySelector("[name=challengeSecret]").checked }); await this.actor.update({ "system.play.challenges": [...this.actor.system.play.challenges, challenge] }); }
  static async #advanceChallenge(event, target) { if (!requireAuthority(game.user.isGM, "Only the GM records challenge outcomes.")) return; await this.actor.advanceChallenge(target.dataset.challengeId, target.dataset.degree); }
  static async #rollChallenge(event, target) { if (!requireAuthority(canPlayActor(this.actor), "You do not control this Actor.")) return; const challenge = this.actor.system.play.challenges.find(entry => entry.id === target.dataset.challengeId); if (!challenge) return; const check = await this.actor.rollSkill(challenge.skillId, { label: challenge.name }); await recordOrRequestChallenge(this.actor, challenge.id, check.degree); if (game.combat?.started) await this.actor.scheduleCombatAction(3, { label: challenge.name, kind: "skill" }); }
  static async #toggleBuildLock() { if (!requireAuthority(game.user.isGM, "Only the GM controls build locking.")) return; if (!this.actor.system.build.locked && this.actor.system.build.advancementOpen && (this.actor.system.build.skillPointsAvailable > 0 || this.actor.system.build.talentChoicesAvailable > 0)) return ui.notifications.warn("Spend or explicitly resolve all advancement choices before locking the build."); await this.actor.update({ "system.build.locked": !this.actor.system.build.locked, "system.build.advancementOpen": false }); }
  static async #openAdvancement() { if (!requireAuthority(game.user.isGM, "Only the GM opens advancement.")) return; await this.actor.update({ "system.build.locked": false, "system.build.advancementOpen": true }); }
  static async #installUpgrade() { if (!requireAuthority(canManageInventory(this.actor), "Gear upgrades require GM or inventory authority.")) return; const panel = this.element.querySelector(".upgrade-installer"), item = this.actor.items.get(panel.querySelector("[name=upgradeTarget]").value), upgrade = catalogDocuments().find(entry => entry.type === "upgrade" && entry.system.sourceId === panel.querySelector("[name=upgradeSource]").value); if (!upgradeEligibleFor(item, upgrade)) return ui.notifications.warn("That upgrade is not eligible for the selected item."); await installUpgrade(item, upgrade); ui.notifications.info(`Installed ${upgrade.name} on ${item.name}.`); }
  static async #rollNpcKey() { if (requireAuthority(canPlayActor(this.actor), "You do not control this NPC.")) await this.actor.rollFixedTarget(this.actor.system.npc.keyTarget, { label: this.actor.system.npc.keySkill || "Key skill" }); }
  static async #rollNpcSecondary() { if (requireAuthority(canPlayActor(this.actor), "You do not control this NPC.")) await this.actor.rollFixedTarget(this.actor.system.npc.secondaryTarget, { label: "Secondary skill" }); }
  static async #shiftAttitude(event, target) { if (!requireAuthority(game.user.isGM, "NPC attitude is GM-only.")) return; const order = ["hostile", "suspicious", "indifferent", "helpful", "friendly"], index = Math.clamp(order.indexOf(this.actor.system.npc.attitude) + Number(target.dataset.delta || 0), 0, 4); await this.actor.update({ "system.npc.attitude": order[index] }); }
  static async #vehicleControl() { if (!requireAuthority(canPlayActor(this.actor), "You do not control this vehicle.")) return; const skill = this.actor.getSkill("piloting") || this.actor.getSkill("driving"); if (!skill) return ui.notifications.warn("Add Piloting or Driving to operate this vehicle."); const check = await this.actor.rollSkill(skill, { label: "Control vehicle" }); await this.actor.update({ "system.vehicle.controlState": check.degree === "Failure" ? "uncontrolled" : "controlled" }); if (game.combat?.started) await this.actor.scheduleCombatAction(3, { label: "Control vehicle", kind: "skill" }); }
  static async #droneCommand() { if (!requireAuthority(canPlayActor(this.actor), "You do not control this drone.")) return; const command = this.element.querySelector("[name='system.drone.command']")?.value?.trim(); if (!command) return ui.notifications.warn("Enter a drone command first."); await this.actor.update({ "system.drone.command": command }); if (game.combat?.started) await this.actor.scheduleCombatAction(1, { label: `Command drone: ${command}`, kind: "interact" }); await ChatMessage.create({ speaker: ChatMessage.getSpeaker({ actor: this.actor }), content: `<strong>${this.actor.name}</strong> receives command: ${command}.` }); }
  static async #creationWizard() { if (requireAuthority(canConfigureActor(this.actor), "This build is locked.")) new AlternityCreationWizard({ actor: this.actor }).render(true); }
  static async #exportCharacter() { const data = game.alternity2e.exportStandaloneCharacter(this.actor); foundry.utils.saveDataToFile(JSON.stringify(data, null, 2), "application/json", `${this.actor.name}.alternity.json`); }
  static async #importCharacter() { if (!requireAuthority(canConfigureActor(this.actor), "Unlock this hero before importing over it.")) return; const input = document.createElement("input"); input.type = "file"; input.accept = ".json,application/json"; input.addEventListener("change", async () => { try { const file = input.files?.[0]; if (!file) return; const data = JSON.parse(await file.text()); await game.alternity2e.importStandaloneCharacter(data, { actor: this.actor }); ui.notifications.info(`Imported ${data.identity?.name || file.name}.`); this.render({ force: true }); } catch (error) { ui.notifications.error(`Character import failed: ${error.message}`); } }, { once: true }); input.click(); }
  async _onRender(context, options) {
    await super._onRender(context, options);
    const activate = id => { this.tabGroups.primary = id; this.element.querySelectorAll('[data-group="primary"][data-tab]').forEach(element => element.classList.toggle("active", element.dataset.tab === id)); };
    this.element.querySelectorAll('nav[data-group="primary"] [data-tab]').forEach(tab => tab.addEventListener("click", event => { event.preventDefault(); activate(tab.dataset.tab); })); activate(this.tabGroups.primary || "play");
    this.element.querySelector("[name='system.mandatedTalentId']")?.addEventListener("change", event => this.#changeMandated(event.target.value));
    this.element.querySelector("[name='system.speciesId']")?.addEventListener("change", event => this.#changeSpecies(event.target.value));
    this.element.querySelector("[name='system.archetypeId']")?.addEventListener("change", event => this.#changeArchetype(event.target.value));
    this.element.querySelectorAll("[data-ammo-type]").forEach(select => select.addEventListener("change", async event => { const item = this.actor.items.get(event.target.dataset.itemId), effect = specialAmmoEffect(event.target.value, { sourceId: item.system.sourceId, weaponType: item.system.weaponType, damageType: item.system.damageType, techEra: item.system.techEra }); if (!effect.valid) { ui.notifications.warn(`${effect.label} is not eligible for ${item.name}.`); event.target.value = item.system.ammo.specialType; return; } await item.update({ "system.ammo.specialType": event.target.value }); }));
    this.element.querySelectorAll("[data-ammo-payload]").forEach(input => { const listId = `a2e-payloads-${this.actor.id}`; if (!this.element.querySelector(`#${listId}`)) { const list = document.createElement("datalist"); list.id = listId; list.innerHTML = [["frag-grenade", "Frag"], ["smoke-grenade", "Smoke"], ["concussion-grenade", "Concussion"], ["emp-grenade", "EMP"], ["thermal-grenade", "Thermal"], ["swarm-grenade", "Swarm"], ["null-grenade", "Null"]].map(([value, label]) => `<option value="${value}">${label}</option>`).join(""); this.element.append(list); } input.setAttribute("list", listId); input.addEventListener("change", event => this.actor.items.get(event.target.dataset.itemId)?.update({ "system.ammo.payload": event.target.value })); });
    this._dropController?.abort(); this._dropController = new AbortController(); const dropOptions = { capture: true, signal: this._dropController.signal };
    this.element.addEventListener("dragover", event => event.preventDefault(), dropOptions); this.element.addEventListener("drop", event => { event.preventDefault(); event.stopPropagation(); event.stopImmediatePropagation(); this.#dropItem(event); }, dropOptions);
  }
  async #changeMandated(sourceId) {
    const old = this.actor.system.mandatedTalentId, archetype = archetypes.find(row => row.id === this.actor.system.archetypeId), roots = new Set(archetype?.mandatedTalents || []);
    const removeSources = new Set([...roots].filter(id => id !== sourceId)); let changed = true; while (changed) { changed = false; for (const talent of talents) if (talent.parent && removeSources.has(talent.parent) && !removeSources.has(talent.id)) { removeSources.add(talent.id); changed = true; } }
    const deletions = this.actor.items.filter(item => item.type === "talent" && removeSources.has(item.system.sourceId)).map(item => item.id);
    if (deletions.length) await this.actor.deleteEmbeddedDocuments("Item", deletions);
    if (sourceId && !this.actor.items.some(item => item.type === "talent" && item.system.sourceId === sourceId)) { const source = catalogDocuments().find(item => item.type === "talent" && item.system.sourceId === sourceId); if (source) await this.actor.createEmbeddedDocuments("Item", [source]); }
    await this.actor.update({ "system.mandatedTalentId": sourceId });
  }
  async #changeSpecies(sourceId) { if (!canConfigureActor(this.actor)) return; const selected = species.find(row => row.id === sourceId), invalid = (selected?.requirements || []).find(rule => { const value = this.actor.system.abilities[rule.ability]; return rule.op === ">=" ? value < rule.value : value > rule.value; }); if (invalid) { ui.notifications.warn(`${selected.name} requires ${invalid.ability} ${invalid.op} ${invalid.value}.`); this.render({ force: true }); return; } await this.actor.update({ "system.speciesId": sourceId }); }
  async #changeArchetype(sourceId) { if (!canConfigureActor(this.actor)) return; const oldArchetype = archetypes.find(row => row.id === this.actor.system.archetypeId), removeSources = new Set(oldArchetype?.mandatedTalents || []); let changed = true; while (changed) { changed = false; for (const talent of talents) if (talent.parent && removeSources.has(talent.parent) && !removeSources.has(talent.id)) { removeSources.add(talent.id); changed = true; } } const deletions = this.actor.items.filter(item => item.type === "talent" && removeSources.has(item.system.sourceId)).map(item => item.id); if (deletions.length) await this.actor.deleteEmbeddedDocuments("Item", deletions); await this.actor.update({ "system.archetypeId": sourceId, "system.mandatedTalentId": "" }); this.render({ force: true }); }
  async #dropItem(event) { try {
    const data = TextEditor.getDragEventData(event); if (data.type !== "Item") return; const item = await Item.implementation.fromDropData(data); if (!item || item.parent?.id === this.actor.id) return;
    const sourceId = item.system.sourceId, existing = sourceId ? this.actor.items.find(entry => entry.type === item.type && entry.system.sourceId === sourceId) : null;
    if (existing) { if (["skill", "talent", "species", "archetype", "condition"].includes(item.type)) return ui.notifications.info(`${item.name} is already on ${this.actor.name}.`); const update = { "system.quantity": Number(existing.system.quantity || 1) + Math.max(1, Number(item.system.quantity || 1)) }; if (existing.system.ammo?.mode === "consumable") update["system.ammo.value"] = 1; await existing.update(update); return ui.notifications.info(`Increased ${item.name} quantity instead of creating a duplicate record.`); }
    if (!requireAuthority(item.type === "talent" ? canConfigureActor(this.actor) : canManageInventory(this.actor), item.type === "talent" ? "The build is locked." : "Inventory changes require GM approval.")) return;
    if (item.type === "talent") { const requirement = (item.system.requirements || []).find(rule => rule.talent && !this.actor.items.some(entry => entry.type === "talent" && entry.system.sourceId === rule.talent) || rule.level && this.actor.system.level < rule.level || rule.species && this.actor.system.speciesId !== rule.species); if (requirement) return ui.notifications.warn(`${item.name} has an unmet prerequisite.`); if (this.actor.system.build.advancementOpen && this.actor.system.build.talentChoicesAvailable < 1) return ui.notifications.warn("No advancement talent choices remain."); }
    const source = item.toObject(); delete source._id;
    if (item.type === "armor" && this.actor.armorSuit && !(item.system.special || []).some(value => /^bonus resistance/i.test(value))) { source.system.equipped = false; ui.notifications.warn(`${item.name} was added stowed because ${this.actor.armorSuit.name} is already worn.`); }
    await this.actor.createEmbeddedDocuments("Item", [source]);
    if (item.type === "talent" && this.actor.system.build.advancementOpen) await this.actor.update({ "system.build.talentChoicesAvailable": Math.max(0, this.actor.system.build.talentChoicesAvailable - 1) });
  } catch (error) { console.error(error); ui.notifications.error("That Item could not be added to the character."); } }
}

export class AlternityItemSheet extends HandlebarsApplicationMixin(ItemSheetV2) {
  static DEFAULT_OPTIONS = { classes: ["alternity2e", "item-sheet"], position: { width: 600, height: 650 }, form: { closeOnSubmit: false } };
  static PARTS = { main: { template: "systems/alternity2e/templates/item-sheet.hbs" } };
  async _prepareContext(options) { const context = await super._prepareContext(options); return foundry.utils.mergeObject(context, { item: this.item, system: this.item.system, editable: this.isEditable }, { inplace: false }); }
}
